# 1. directory
root_path: "../../data/LA"
res_path: "./results/LA"
# sampling
flag_sampling_based_on_lb: False
# random seed
seed: 2023
test_interval_ep: 4


# 2. training
labeled_num: 4                # TBD:   4, 8, 16
max_iterations: 15000
max_samples: 80
base_lr: 0.01
batch_size: 4
labeled_bs: 2
poly: True


# 3. supervision
ema_decay: 0.99
cutmix_prob: 1.0
flag_ulb_loss_type: "ce"
conf_threshold: 0.8
consistency: 2.0
consistency_rampup: 40


# 4. alternate --- no use
alt_flag_epoch_shuffle_teachers: False
alt_flag_conflict_stu_use_more: False
alt_param_threshold_self_training: 0.8
alt_param_ensemble_temp: 1.0


# 4. alternate
alt_flag_conflict_mode: "pixel_confidence" # always_tea, always_stu, random, pixel_confidence
alt_flag_updating_period_random: True
alt_param_updating_period_iters: 19 # half epoch
alt_param_conflict_weight: 1.0
